// Package engine provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package engine

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWUW/bNhD+K4fbHlZArdOke9FbiniYH4YaTbGXLSgu5MlmQJEcSXk1Av33gaIky7Zc",
	"DFubJ8sk77vv7r478hmFrZ01bGLA8hk9B2dN4O7Pe5If+a+GQ0z/hDWRTfdJzmklKCprFk/BmrQWxJZr",
	"Sl8/eq6wxB8WB+hF3g2LpffWY9u2BUoOwiuXQLDEldmRVhJ877AtcGUie0P6nv2OfbZ8AR7ZKYTOK3B/",
	"sOiBu8SMXJy3jn1UOV+SIymdv6aYd906ywwGNYdAG8YC494xlhiiV2aTQlYmRDKCzzH6QoCSbKKqFHss",
	"sLK+poglNl699lyx52Q8AxwixSacw/766dMa8iYIK3kKqky8uT6AKRN5wz6hRRX1DMf7rfWxDzI0dU1+",
	"P8clL5wadzmFtPffYmwLTNpRniWWf+TdMe6B8sNoZh+fWHQyW+5INxR5IvXjsiYlKMGfp8X5mrbu8/nV",
	"cPyU2hne11nlhpyjpVlElp+dtzsl2c8UJHuC4QQMNvC4B2e1EglrTi7/N+TLirtdrz9++H15B69h0HRj",
	"xJbM5pjWn+a3D3erX1ZHJ/+mALWVSRsnh7FANk2d8jt4wAIHiEmKL+jlLOJiJsFjVHMVO83BecEci25q",
	"SalSMkivJ/vRN1xcqF+yVFU/6eCnSvMX9agZcvpf4Rmb0+CS53PObTdxKjtMVRJJ/ZdH4u16BZX1Oet7",
	"4CzRjpKxEfiLs4ElRAtsJDSBfXg1tl6J62y2NBtlGJYH69v1CgvcsQ/Z4e4tabeltymr1rEhp7DEmzdX",
	"b26wQEdx2+VzwR1SyTMNbPPvyYjpDwYg6OsNQ72HiwdoQ2kNSGvo75eU6kFpKTrJkX2dgiCXtEEayMi+",
	"uYBgopdU3y7IlZwQGJjmKnGI763cf7u77cRLeyyHJLRuYXLTX19dfQf3/eSauWUnxQ+NEBxC1ehU7neZ",
	"yBz+SHgxeZd0Jjff/1nQa9fzU56fccvTp8q76+sX4yCsqbQScXiaFPjzv0na3Guqe9b0F/VBnWMrONpr",
	"S3JsiemNQZuQJsuhkPjQUc7PprT3jI3XWOKCnFocWvphNH6ej28yVsbuSS4N1XwkHWwf2n8CAAD//8Id",
	"/aXACgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
