// Package engine provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package engine

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWTY/bNhD9K4NpDw2gxJvd9KLbBuuiPhQxskEv7SKYJUc2FxTJkpQbw9B/LyhKsmxr",
	"F/1KTpZJzps3M2+GPKCwtbOGTQxYHtBzcNYE7v68J/mR/2g4xPRPWBPZdJ/knFaCorJm8RSsSWtBbLmm",
	"9PW95wpL/G5xhF7k3bBYem89tm1boOQgvHIJBEtcmR1pJcH3DtsCVyayN6Tv2e/YZ8tvwCM7hdB5Be4P",
	"Fj1wl5iRi/PWsY8q50tyJKXz1xTzrltnmcGg5hBow1hg3DvGEkP0ymxSyMqESEbwJUZfCFCSTVSVYo8F",
	"VtbXFLHExqvXniv2nIxngEOk2IRL2J8/fVpD3gRhJU9BlYk310cwZSJv2Ce0qKKe4Xi/tT72QYamrsnv",
	"57jkhXPjLqeQ9v5djG2BSTvKs8Tyt7w7xj1QfhjN7OMTi05myx3phiJPpH5a1qQEJfjztDgvaes+n18N",
	"x8+pXeC9zCo35CUt7k/Iz/+ZYIGBNYuE5bzdKcl+prrZCoYTMNjA4x6c1UokYv9Ae7fr9ccPvy7v4DUM",
	"6m6M2JLZnGL+bn75cLf6aXVy8k8KUFuZVHJ2GAtk09Qp04MHLHCAmCT7GeW8kNe5PI3xzVXxPNOX2nIs",
	"ukkmpUppIb2e7EffcPFMGZKlqvrpBz9Umr+oR82Qi/wKL9icqzB5vuTcdlOossOkJZE64vkxebteQWV9",
	"zv8e+uR1lIyNwF+cDSwhWmAjoQnsw6uxHUtcZ7Ol2SjDsDxa365XWOCOfcgOd29Juy29TVm1jg05hSXe",
	"vLl6c4MFOorbLp8L7pBKnmlqm3/Pxk5/MABBX28Y6j1cRkAbSmtAWkN/56RUD5pL0UmO7OsUBLmkDdJA",
	"RvY9AgQTvaT6dkGu5ITAwDRXiUN8b+X+/7vvzry0p3JIQusWJrf/9dXVV3DfT7OZm3dS/NAIwSFUjU7l",
	"fpeJzOGPhBeTt0pncvP1nwq9dj0/5TEYtzx9vry7vv5mHIQ1lVYiDs+VAn/8O0mbe2F1T53+8j6qc2wF",
	"R3ttSY4tMR38tAlpshwLiQ8d5fyUSnsHbLzGEhfk1OLY0g+j8WE+vslYGbsnuTRU84l0sH1o/woAAP//",
	"YqrtXdQKAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
