// Package engine provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package engine

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RXW2/bNhT+KwS3hxVQ66TpCtRvjq2gGtLEs50CxRYYtHhksZBIjaSceIH++0BSdyvx",
	"lnpPtsRz+c53Ljx6wqFIM8GBa4XHT1iCygRXYB8uCV3AXzkobZ5CwTVw+5dkWcJCopngo+9KcPMOHkma",
	"JWD+UtCEJXiMA74jCaNIOisoI5KkoEEq7GGlic4VHn84O/OwZtro9jWwh/U+MweXk9l64f9+5y9XuPCw",
	"CmNIiXH2s4QIj/FPoyaQkTtVI19KIXFRFB6moELJMgN5wE3h4SshN4xS4K+M9ZvIERWIC41isgOk8ihi",
	"IQOuUQYyZUoxwRXSwjxGQqZIx0whkYG0xjuMXDSMzGtlRIEzoA0nc3/xJVgug9ub9cy/CfzZCZhZxYBI",
	"rmPg2kQNFOUKJKICVBNbE9AL8RQeDrgGyUmyBLkD6XweZ/eHc+ucImW9InCCHp6LhIX7qeBRwsLXlvS1",
	"eAD5NpNMSKb3KLM2kZYMqOFC7EBKRgHFbBsfCnaS/KmVZGcmrLA1Kb69Dqbf1tPbm6vrYHqK0u+5QhvQ",
	"DwAcJd3ACKfDMTBQBsUCvkOogb6SxhIFPBpxppM9kqVBpGNotX9D18cDuiqVhq6F/5s/XZ2kEXo+OrAK",
	"D99x0yVCsr9fzcFXO4JazWb6KZRAzSNJFCLSuWTSFRcJQ1DK9ZkEJXIZQoei84aiSddsZaah6u5mcrf6",
	"7N+sgunkNIz1XFqQJfhNrtEDcRMkk2LHKFAkpJFhbhTjogZg7556WGTSjBTN3JVUkffU8z2z74G6bkcp",
	"KEW20ESrtGR8a4Ms2epb+LxazZE7RKGgRtdMNaLxGDOuL943xhjXsAU7U0q6+8aWsZC6xKLyNCVyP4TF",
	"vegr29CROUPM1kLEQLbh5JK9lRCBBB4OxFh4uE73+A93WsddQb6v1cTGVLiB4+9IkhMNrUu/y76ZqCyE",
	"NeNKE+P7SKksnXxQifehHdh7GZVbTQ5hQSlB1z8M0MMKEtvw67JO5UB2nVZVyRJVOmjTGpL/ofYm8/ni",
	"9qs/Q29RyT3KeRgTvu3a/JN/uZ0FV0FH0vRVKqipkp4w9jDwPDVMVx6whysTLbKfqZwXeB3iqY5vKIt9",
	"pg9rK4PQTk9KmaGFJPPWuZY5eM+kwWiyqBo7v0QJPLJNAsgl+Q0+QNOvQuP5ELMRYzwS1XQndmd4ft2Y",
	"zAMUCVmtBCV5FpIZe/CYCeXmOHC3Vak3+OBO8/mWcUB+oz2ZB9jDO5DKOdydkySLyblhVWTAScbwGF+8",
	"O3t3gT2cER1bPkdVHYxhoK2F++0NnlJQIYLKjKMq4/UOT7bEvEMkSVB50xmyK28mPmpW/NSEQTJTHSSx",
	"64SrGERQq2LqdTGgLQCL+vovvV4Kuj/d5tjzUnQLwpSafdH6Enp/dvY/uC/n2cBV2kq/yu2tH+WJSfgH",
	"B2TIfg141Ppusyrnx1U664xVujiu1HwyWY2PxzXqrdEqfDqu0NvZCw//+m8YGPrwsAtGeRc3pdb6Nt0n",
	"gtC6vttznGyVGRRNVvC9TZr7wjBnTziXZqcbkYyNmg69r5WfhtfL1pSoW8G45CSFTh3g4r74JwAA///r",
	"NDzprQ8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
