// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xb/3PbNrL/VzDszTiZEWVKtvxFbzJvVEtJ9M6xfbLd12uV50DkUkJDAiwA2lYy/t/f",
	"LAB+k5jYTdzezf3SxiIBLBa7n/3sLvjZC0WaCQ5cK2/42cuopClokOavC5GwcD2NLqhe4d8RqFCyTDPB",
	"vaF3tQIiQYlchkBYBFyzmIEksZBEr4BkZnSXvMuVJgsglNzShEXudzIdz7leUU1CwWMhU0W0IKPJhd/r",
	"94mE33MmIUW5hnPuk55/sEfCFZU0ROlIIvgSfz8VdyBDqoAkoPFJh/A8XZh/UB6R1TpbAVdE8GSN7xth",
	"lKZSkzumV4S6ceUz4FHzCRHSTTnnXseDe5pmCXhDb5mIBU18muuVb/fkdTyGmslQXx2P0xTfy5wWvY7n",
	"thV5Qy1z6HgqXEFKUbUpvT8FvkQ9H+x1vJTx4s9eB+fTIHHm//uV+p/ev8D/Bv6x//5z0DnoPbg/37/8",
	"7795HU+vM1xWacn40nt4eMB1VSa4AnOqo0QCjdaTe6bsoYeCa+Aa/0mzLGEhxRPe/U3hMX+udowGoClL",
	"vKGzDKuo6ZjsbOtih1C7DgG7EOpGacpDFC4IDw4PgoPAP4TjA/9gEIIPR8GRDz16cLS3iPePjxZex1Oa",
	"6lx5w/3guONppo3eZ4XNbS3gdj46nU1G43/eTH6eXl5deg91Pf9NQuwNvR92K7vftU/V7kRKIa3Cmpb+",
	"pRUfOt6PNJrB7zko/Y2afM0giciOhKW4CUUEOyRFM+TC+AykmV43VXd4vLcfxXvg7y8O9vz9/vHCXwTx",
	"wF8cRXuDAMLewQAaqgsq1U25dUFpRSY1dy+1Nz37aXQ6Hd+MZm+u303Orp5Bf19Z9qHjvRZywaII+Ddq",
	"8J8iJ5EwGlvRWyAqj2MWMuCaZCBTphQT3KBLBhKRhugVU0RkIM3kTfUu+uFetA8DPz6gh/7RcdDzF2EE",
	"ftzr7+0PDg7xl4Z69yr1XpTLkQg4g6jS6sVk9m56eTk9P7sZT86mk/EzqBUBGD0OkTekGiKSK5AkEqAq",
	"bVQq+IoGHjrelCPE0OQS5C1Iu+a3nceIk5zDfQYhigQ4ExFhmEsJEblbsQRIJkUISjG+NJHC2UXzIHrR",
	"4VEQHAb+UUwP/cODKPbj4+DYj/uLw+P9kA6C47B2EIOmndvNEGV2Y4Wom/jVZHY2On0W025b6aHjnQn9",
	"WuQ8+j6AbQXW8oANDDW1drwYHMTBgPoH0dHAH+wvIj86pId+FMSDwz6FvaND2jDf/RZgxbljI3ypsrPz",
	"q5vX59dn4+eE02qdh453zXGTQrJP8K1K+8mgTM0l0OpDCYab0EQRKqGgFhG6Aw3RDK03FFSmqU/as4Dg",
	"wyA+8NH7fboIIx9qeNDQZ6/S56gpSBn8S6Ven42ur95Ozq6mJ6OrZ4GEjSXNttx2F7kmd9QaTibFLYsg",
	"Qm7DFGEWn3F9o0Iz+HsgoAD8GSwFUWuu6T1hvBHlYox7TV334ei41zvs+ccxPfKPDuPAD2iP+v3w+DgY",
	"hIuD4Diq67rfr3Rdyb3p7K9H09PJ+OZiNjk5PxtPr6bnZ8+g6K31Hso5DacqtdccZn4mBR0jsUgScYcw",
	"OHt9Qg6PgkNyIcUigZSMjS6VIbGGFR/vded8zi/s0SmitMxDncsSY5mh0VYm5OCjiymJKUtyCapruGsm",
	"EfI1szywOK1NGd/mKeU+Eh26SIDAfZZQbqdVGYQsZiH6jg0hFtd5CETElvVb+btzfrkSeRIVtkZoiFOY",
	"KTcljeAWEhTNyVlx7G129JhJbxPguo1t7vWas9/zluyFqWqvjQjGQ+iSawVxnuCrc64lDT/iCeJBRbDI",
	"l0vGl5v7eCJps2rxhl4umS8hBrNg25YKJ9g6vKurC2IfElRYXQpDBcslGNd7/WpqxjUswYQu51OP2IXK",
	"05TK9ca5EzNdfetP4ZzVvuwPW8c0m5JSHcVprQv6UF+6S67w8JgyT0LKBWchTebcniKqxJ0Nz1Nv+Os2",
	"3e3UYl1nM5foeLPJ5fn17GRyM/n57ej6EmG704oxHW/04/nMPj+/vro5f30zG529mXgd7/ps+u7idILL",
	"mcclH8FHo59G09PRj6f44ngyGp9Oz3Cxk8lkbF7eDBqdFm75vnEA2zt8qp091FPWXz13ts72CkN5Xw4T",
	"i98g1HiMb4EmtmbQxJystZJwUhwTweeFRdUCcrWZlZ0Y5aLROU/WRSr9dA8xM5ByE5tzrx9Vgxu6te+O",
	"d+9TyPxScLthJIgKxznZ33e8LMklTerbQS6cgEYJXWmA8WWeUFl/yS1neaCfUk6XILtRmHaZ2HVvobCn",
	"TGlDIBmomYs124oonpAUlKJLMNCXMKXRrzI33MScKSrI1GJsKNrrE1wCdcgjKiOSgl6JqFG1aYs4HO71",
	"TUaXcKPFR5vvbWQ0+LORQ4KWDG4LF8eRBEeicUhQeaJVl0xjmyCbEo3Qc55JUMB1B8dIMHSPC5IKQ/vs",
	"INyPgQgjAjFpEMUYgPitbMhyyXdGpcIosyZhwqo9VQYD6/+5/SX95dMvP/+Dnf92fRf/49WrNlArlLm9",
	"YaNGERc1scJyFEmpDlcb+REJJdMgGRJ4piFVj7EXm0RUsOpRKel6y55L8do82c3RYj1O2UhRyPnFiLw4",
	"z4ATl7iMlsD1y819WQbjliMRxIzbFBZpv2PJeQKK5CY3NPQRIdscTkg5nooKRQbRnGtBIhYb6NIkQQah",
	"yIs3p+c/jk7RHq4vJ7OXGA1gbezAKBQiQpcU6cCcO6UWayV0AZjFJRBqIS3vglua5CaxZpxkkgnJjLFF",
	"INvMO5RANdxolrZ42xVLQWmaZuRuBbxWIDUMxg6NXPQy3NiYZq6zXPu2eIkS0VwLJE4hTZI1UaDROnEu",
	"m34a/V4rUGR6eU6ODoIesVBvK3Uo2SfBTVHAevJ+sGnT/aB/4Ac9Pzi+6gXDvWAYBL/UI0ZENfhmi0/A",
	"4IYKNjVybv5BE2KJKCB9Kp+XtMLmvIpkucyEspawgBW9ZQK3e5lnmZAaHUZ+jMQddxvWLSRsgrQTnYu2",
	"JmYW4GgohVKEJjalZ/g+4wXPiPLQcn5+y6TgOMTr1Iu3/WD/qE0RTGUJXd/YkvAjzApf2qqil7RmnRWn",
	"v8LtMj7npuyDBE7G1OyvgrIFVFq9hU2NvDHVBbKRNV4Uxez6vgaDzar01ibBsPvI7i+meaILw2hu939X",
	"gPhc9wGmiKXXOlmbTOEWumTMlJmwDEYO0PWcV54Z5dKw7waIRBAyU/Xb2HDDTBdCJEBN8YtFT08NNo6k",
	"zVfxAOacpWmuzYHSWIO0Ps4EN6BEpuMC0ITzAzxSm3NARG4ZnfPfc5DrijATW80wk/wXYXEj7+nUYIAs",
	"gYOkGjVGrq+nY4MLr02yqWo9FleGQVEEv8V9bqusvc3xR9oVgX/8SMfiURwx4HxTgLOpREQRs2q7aGDw",
	"1yHI+zusfTQdDO5MIvbbQpCJDjbvcxbp4gRhPBQpWlgRL7rIH+qGW9miOXsWG/AwIqty4loQF1zDve7O",
	"+RRPcCPw4ITNI21bCC0RF6nJNOcnIk0Fd/N9hLVtnNWQalhDsA6SN8xUO0X2jW/gAASTGxYNbTG5Mn98",
	"5hBxWPzDQBU+kLBkgg/JEsRS0mxlyLz9ER9rBrIahH+RF0hm8LVOSSM7BHTYfdm0v89eHWuHXrUFYzhL",
	"e6658oEq7fdMVgLImov5a/SnYjXteUhZmDRpiEN9F0DnJU3a/Vx09B7mXtexyS/BwBdi9Bd90az8FW8s",
	"hWh1y5rnlS8+oWP4qP/ZBW7ak/NLJGTNeE1qhcJNnPwiLM6NqVgGNyQjnAFM26Zu6UV8NvpcKw0pDkKy",
	"1xhSvm48parloE03OChGlAbNWzGQVIbWgg3VGxIXJv15HgR7QK5V0Qt2NQQrM+bml5NZM/kuH23r1PHJ",
	"Rrg0XYymei8K3mlxCzfklOzkNmzJcFLbDS8a4Kb/M+crtsRgW9JXQyMbu46ZVNqo3xbQJeVLGJKe3wuC",
	"wDbfe0EwJCfOo3at4suwbF4Jev4AX7oscsL600FgJxuihH4pSvVK3cZ7rWWqlN6zFNWN85iI4/5sq2CV",
	"9cL2WwuYrZjcwinSVIWsmZpsA7H2HsJcm4ZVg63PeR2Iq8sNW/Vul2iCndGxsSLjIRkNP2I2a4uGlqzY",
	"1KdLHI4XlQOD4uNioLMU9AlxtxsBN7caygQdoaMIjCQRSxaSBVUmNBHGs9wg/KyspEVUUxJLkdZ9F/iS",
	"cSjEr3IwpuwuXahzOYvZQp7hr1VDcRu2iv3mevUJp27sg7wiMU2UWdP+8HnOiRW4iy7bbbY5X70iCFQb",
	"70iRAD6aezRKGZ97c/5gxKiTlcFg7+BRImu3802JXEKVdur4o9mcG9WMFqhoytckFRECWIWUz5flDYb7",
	"g+/I8jaKCY1Mpxk56n75h4tnm9H3hkUPjVJaWcVo1M7K0PjV2pl768E0ehiPRdH3oqH2hp+322yTCz8U",
	"aZYwyjWZTS6vbLdFSGJmRr741ZIIq7LK8cm74o13TqqyRmUntVQB38W/J3xFeWi9HbmvUDRR5MVocvFy",
	"syCnbIuiUKkvJAOubaLNlrzjmCZKezK7Htf812zlYqMoZeT64Qfyd1iT10B1Li26v86TpHUC5xdW2QW/",
	"dBm7ecHW1fwq7bGMCQ3fL3KYiEzHdpkE7hnyhpglGmTRc8lQ3WbRUpaSTUnIEup0Zd3LzNQ8PtsZWFEe",
	"JYwvjaMkLARXM3WXuEYZDVdA+t3A63i5NLVbrTM13N29u7vrUvO4K+Ry141Vu6fTk8nZ5cTvd4PuSqdJ",
	"rbXiNQ8cz9XreLcglbWv2x5NshXt4RCRAacZ84beXjfo7lmWtzLJTlHzHX72lqC/WOoOVxB+NPretjW3",
	"dHlw0whJC+i3VZ29dnWsHwRP6Ag/rbX6tqhXb3nXpcsTmCJFSd50V23DaWNf5tFuvcLaqopThmyw9D0D",
	"lKpmiZUVdSr7slcIDbey5SRj/q+LxwaEjV9+sEM+1HJ1s8LJ5NRXem27qBLsTSQT0D/UgPHVjmWJOx/M",
	"E1dGeYVo+2H7XeSYO2R0NiYbLxrhzp2wNdmM/DeLdU06J0JJCVX4gbxwIfll8xmq0UpRR3YzxPxaK3oW",
	"727ZU70fYey3umT663e2AE6B3rprcq4fiykbElrzrunVWjVsNB8+1HiPhFsmcmWQ0rZEtCBL0M11n1j9",
	"NzdATeWmdgW06nnUbx5sRdJNZbyzpNcx+rJRUCY5OpfchHm7V3t3i6R07Z7NeQyYEdQ7Jjkv4bZT0Ekz",
	"3SDokmJBm2swRZBtd1v4edsuU3pvFazYJ2hstJbffB+131aR9caaf5mMMcuStb2kAKal1SVlobiKHov1",
	"lit+GJJmC6HukR+Ghnbio5KuTqxWvtep3bttbr2d/j826AtGaDf+xwwQcxHqK0CXxVCcuH6V4bTGagy6",
	"kMW6SyY0XDmyayubc265i+W0O1SFO6i7HVxip4s5TWl7O3Us2jFI6w7M5Ke4mNFw8Rr+u45H+HcNiVpO",
	"po5123BWodwmnnU2RjaPo/bsC1ov0LfdHzZn2DyQ939iAG7tEreE40aPEhH8oePtWznapi/l3a3djTZD",
	"eo8PaVwCNIP2Hh9UXSB+6HiDp0jWdtm1STHMpmsphaZLk4aUYey9KYupFqpxYixIEUo43G11QE3xHxM+",
	"B9Rb1f81oXPuiDFVyNMNBSa3jNpAxqIPZKMzYIB9qxsw5y6HvGNJUvYEqpbAVpy2kl9U1cSvxOmye7fF",
	"4afjrU7Jt0g357N6X+5Fmc32+y+/+knIZfV1R7LxdQg+PsG0jnFbrE+e9vkIjpsUH4Z882chG8jAIu8v",
	"+gLkvU3RQekfRbR+NgC5KLPmzS9bHrZgq/enrLpRKXXVPNtLJyo3t3vjPElQ6yugkfuu6VTYldsvmrlK",
	"djFN7RpSJWDt0pDLAmnGuu7XbijS3dve7tdr9fU7WG1f7fxbo+x+cPz4iOaHRjiq33981OYN5OfD9BNX",
	"sKzhcjuy1zPKWrfHmksCuqUqODa/I+g3usMlvrrOB0SsqJmGlLt7RjmPBAcHeUjbFekH++RMGKwCrong",
	"NWsmRoaykVwt4eBVzbnSUvAlCQVXTGng4Zr4BCEkzcztLpM80Khxza4SL1nb1sycFytZjHb5xr6RTRPz",
	"eUNbGLG6+FIYaTvF6pXdxjeHLfxnf1v3zu/t0TT9nrzggjjYefmX+sf+4yPKT0Sez8St6ksr/BJxaS2R",
	"zGy+bYzYXkcsyMtiTZhWxIVlY9juxh/bvBnYI29g62Jgm5G8Af0nWUjw14UaV6LYDDb/+XaGh/yYkWV5",
	"i5Fd2yosodx+vVTeNV27e3jxlwq4j9vePrGzb5pfx3wokCtQ5OL6as4ZVxrRT8TkYnR18tbQ1a+v+8MP",
	"trI8q36f81GSkKKX7RLi1LUDyw9sXJHf0S+L2DXeO+duJfMWcM1kDZFtO2dVmy6imhYCTctGuvlKQtl+",
	"XfVJiROpFmdsg8km0lSv8P8sMn9VZQXyohoQrihfQrTRqH+5lWz7pNYxa/H1UZYl6+fz9n8tk/0L4aXo",
	"CG6Dy78vL/zX4JFz/K9DkhliprCWZ9s4yNx3q4bL+3LodsbbaG41Gn21SoHL7sp1H94//H8AAAD//2FP",
	"utNmQQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
