// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8R7a3Pbtrb2X8Gwe8bJDClTsuWL3sm8o1pKqrMdW1u2e3pa5TgQuSShJQEWAG0rGf/3",
	"MwsAbxIdZyfe7ZfWIu7r8qxnLSCfvUikmeDAtfIGn72MSpqCBml+TUXCos0knlK9xt8xqEiyTDPBvYF3",
	"vQYiQYlcRkBYDFyzJQNJlkISvQaSmdEd8j5XmiyAUHJHExa772QymnO9pppEgi+FTBXRggzH06Db6xEJ",
	"f+ZMQor7Gsx5QLrB0QGJ1lTSCHdHEsFX+P1c3IOMqAKSgMYWn/A8XZg/KI/JepOtgSsieLLB/mYzSlOp",
	"yT3Ta0LduLINeNxsIUK6Kefc8z14oGmWgDfwVolY0CSguV4H9kye7zGUTIby8j1OU+xn225Z7PmeO1fs",
	"DbTMwfdUtIaUomxT+nAOfIWCPjrwvZTx4mfXxwk1SJz6f3+jwacPr/C/YXAafPgc+kfdR/fzw+v//w/P",
	"9/Qmw3WVloyvvMfHR1xXZYIrMGodJhJovBk/MGW1HgmugWv8k2ZZwiKKKt7/XaGeP1dHRgvQlCXewJmG",
	"ldRkRPZ2hbFHqF2HgF0IhaM05RFuLoyOjo/CozA4htOj4KgfQQAn4UkAXXp0crBYHp6eLDzfU5rqXHmD",
	"w/DU9zTTRvCzwuh2FnAnH57PxsPR/9yOf5lcXV95j3U5/0PC0ht4P+xXhr9vW9X+WEohrcCapv7Uio++",
	"9yONZ/BnDkp/oyTfMkhisidhJW4jEcMeSdEOuTBOA2mmN03RHZ8eHMbLAwgOF0cHwWHvdBEswmU/WJzE",
	"B/0Qou5RHxqiCyvRTbj1QWm3TGr+XkpvcvHz8Hwyuh3O3t28H19cv4D8vrDso+9NOBo3Ta5A3oG0k3yb",
	"LIec5BweMog0xARwJiKiKJcSYnK/ZgmQTIoIlGJ8ZUDK7agp4W58fBKGx2FwsqTHwfFRvAyWp+FpsOwt",
	"jk8PI9oPT6OahPtNCdvDEGVOYzdRF+71eHYxPH8Robat9Oh7F0K/FTmPv8+1W106FqCMaRoHaErtdNE/",
	"WoZ9GhzFJ/2gf7iIg/iYHgdxuOwf9ygcnBzThl0etrg0zr00my9FdnF5ffv28uZi9JKOXK3z6Hs/o3Ea",
	"wXyP8RVGPoOVIGrDNX0gjDc8e4m+3pRaD05Ou93jbnC6pCfByfEyDELapUEvOj0N+9HiKDyN61Lr9Sqp",
	"VfveNrO3w8n5eHQ7nY3PLi9Gk+vJ5cULSG9nvcdyThNHSuk1h5nPpAhBZCmSRNyjA87enpHjk/CYTKVY",
	"JJCSkZGlMpHbUIHTg86cz/lUijsWgyJKyzzSuSy9mxnuYPeExGM4nZAlZUkuQXVMwM6kyEBqZmNfoa3t",
	"Pf6Up5QHCO50kQCBhyyh3E6rMojYkkXIT/SaqQJReARELC3VsfvvzPnVWuRJjB9ww4RGOIWZcnunMdxB",
	"gltz+6yIxW5EYKpgRDFZ5JrcU+uFbpl4N+jXbWz7rDec/Zm3UDamqrM2sJNH0CE3CpZ5gl3nXEsa/YEa",
	"REXFsMhXK8ZX2+f4ykBlxeINvFyyQMISzIJtRyqcYEd519dTYhsJCqy+CxP+yiUY1we9amrGNazAgKbz",
	"qWfsQuVpSuVmS+/ETFc/+tfE2epc9sOOmmYTUoqj0NamCFz1pTvkGpXHlGmJKBecRTSZc6tFFInTDc9T",
	"b/Dbboj3ayjrb/Mn35uNry5vZmfj2/EvPw1vrq7H2KsNY3xv+OPlzLZf3lzfXr69nQ0v3o0937u5mLyf",
	"no9xOdNcRkJsGv48nJwPfzzHjqPxcHQ+ucDFzsbj0XjkfWiIdnfvX2tBj3UC/pvntOasqjCBD+Uwsfgd",
	"Io0KOmdKm7DIQM0cju0qrGghKShFV2DcKmFKo84yN9zg2QTPYpIbC3MHPYJLoA3zmMqYpKDXIm6kQW1o",
	"xuFB32Z0Bbda/AG8JUfDz2YfErRkcFeYD44kOBJNWYLKE606ZLK0hNPkPELPeSZBAdc+jpFAqMTISVIh",
	"oRyE5zHmZ7aARigyiviC2KAsHDoym1GpEME2JEpYdaZKt7D5r7tf018//frLv9jl7zf3y3+9edPmMIUw",
	"dw9sxCiWRZJZ5KeKpFRH6y3WRyLJNEiGtIRpSNVzkdFSo8plPSol3ewYVrm9Nltyc7RYjxM2hj9yOR2S",
	"V5cZcOLo2HAFXL/ePpeNjm45EsOScSDI2IRkn2yskXkCiuSG8RpqgnBglBNRjlpRkcggnnMtSMyWxnk0",
	"STA6KfLq3fnlj8Nzn1yPL4YX1z4axs3VePYaIQc2xiCMZCEmdEUx5sy5k26xaEIXgCQ1gUgLaYM73NEk",
	"p0jSGSeZZEIyY3UxyDY7jyRQDbeapS1ud81SUJqmGblfA6+VHkyYtENjB5GGgBkbzXWW68CWBXBHNNcC",
	"o3NEk2RDFGg0U5zLsmsj6BsFikyuLsnJUdglFnVsCow7+yQ4kAykdenDcNu4e2HvKAi7QXh63Q0HB+Eg",
	"DH+tg1dMNQTmiGhNNL7kyaaoE+x4QEME2xK5NH/QhFi2Axijy/YydllKr0iWy0woaxILWNM7JvC4V3mW",
	"CanRc+Qfsbjn7sC6JdKPkdugl6HpYZyKnO3V8IvQSAqlCE1sxsKwP+NFMIvzyBJLfsek4DjE8+tVkV54",
	"eNImCKayhG5ubbHlmfCNnXbqU2Xs3GSF9td4XMbnPFeAHFODXFJzvgrTFlBJ9Q62JfLOJE9k2JTHtCgT",
	"1c/V72+Xe3YOCYZCxvZ8S5onujCM5nH/ew0I1HUfYIpYDqeTjaGjd9AhI6bMhGVUcsiu57zyzDiXhuI1",
	"0CSGiCkm+DZ0N8x0IUQClBsWGn89/9xSSZuvogLmnKVpro1C6VKDtD7OBDegRCajAtmE8wNUqSW2EJM7",
	"Ruf8zxzkpmJlRPBykv9H2LJBrv0aDJAVcJBUo8TIzc1kZHDhrcloVK166bJM3Irgd3jOXZG1FxBfsA74",
	"LIgYZL4tkNnkunHMrMymDQD+Mv54/4RNgHaDIZ5JBH6IMV0yocFmFs4cXZAgjEciRfMqgkUHWUTdaitD",
	"NIpnS4McZsuqnLgWyjFhf9CdOZ+g+raiDk7Y1GfbQmiGuEhtT3N+JtJUcDffH7Cx9egaTA1q8OUjhcNc",
	"yC/yO+yBAzRwyvUtiwfuz5r9YzsijWm1kNNoc3A5KP4wOIYNElZM8AFZgVhJmq0Rv9xHsyYDWQ3CX+QV",
	"Uh7s5pdk0yego87rpnF+9upAPPCqIxrDWlm95yoAqnTQNewZpDfwivlrJKniPlnrRUJZlMHmIiS46Dov",
	"ydT+57KQ/jj3Oo50PgUST0TwJz3VLP0FXy130eq0Nb8sO76Eg7oTt+eHV8jbmtGc1GpV2yj6JGjOja1Y",
	"ojcgQ5wBzGVM3RWK6G3kuVEaUhxkWWFjUDkAeRHjhNbqJ8bucRxSyPZRxgWrIegMDYqLcapBHtcMJJWR",
	"NX1DIAfEBd9gnofhAZBr62/FzxtVXOW4bNge3fM9exxMSK/Gs2bWWfbZ1ZFjr43gbErCTXVNC5ZrgRIP",
	"6pTmzmO4mWHA9laruMgia3oHc75mKwztJVk2pLUhjSWTSht1/myLD5SvYEC6QTcMQ3uJ1g3DATlzLrpv",
	"FVmSANMl7AZ97HRVpKL11n5oJxvgDoNyK1WXus90WysvKX1gKcod5zHxzf1sK8qUJbD220dMkkxK4wRp",
	"Ch3W7E2Sg+D+AFGuTfW/kRvMeR35q0vKnRKuy2/Bzui4X5FokYxGf2ASbetglhrZjKtDXOBw2GDDxqgY",
	"6CwFfUzc78fAze1kWRdAKCoiMUnEikVkQZWJhYTxLDdeNCuLQzHVlCylSOtYAHzFOBTbr1I/puwpXWx1",
	"GZI5Qp7hV4KRn7bDYHHeXK8/4dSNc5A3ZEkTZda0Hz7PObEb7qArd2r5AcTkzRuCwLfVR4oEsGnu0Thl",
	"fO7N+aPZRp0a9fsHR8/SZnucb0obE6q0E8e/mzu6Uc3og4KmfENSESOwVcj7cjllf3DY/46ccquG0cir",
	"mpGo7pc7FQ7fewgoZEERWe2rAusC9dpIPZzjLFmSS5rUIq3ne4rxVZ5QWV6iV/hrfwcp5XQFshNHaYeJ",
	"fdfr0dxdML4UxVUOjbQ3+LzDW1GqkUizhGGAmI2vru0FgpDEzIwE9YuVGFblsKOz90WP925XZWnMTmqp",
	"B/bF32O+pjyy3o5kWyiaKPJqOJ6+3q4DKlt1L0QaCMmAa5vWsxX3HbXF3Z7NbkY1/zVHmW7Vwsy+fviB",
	"/BM25C1QnUuL7m/zJGmdwPmFFXZBaF19wHSw5bygSrIsA0PDD4qMKSaTkV0mgQeGPGTJEg2yuEbIUNxm",
	"0XIvJTuTkCXUycq6l5mpqT5b7F5THieMr4yjJCwCV6p1jzGGGY3WQHqd0PO9XKLBrbXO1GB///7+vkNN",
	"c0fI1b4bq/bPJ2fji6tx0OuEnbVOk9ptgddUOOrV8707kMra112XJtmadnGIyIDTjHkD76ATdg4sa1yb",
	"7Gq/Xs9cgW4va6rK5Aw+qJoCKuH5lVjtCxhDKWzNxmj9bdFssMeY40c75GMtITYrnI3PA6U39j5MgjKJ",
	"v4ljH2t48GbPkqO9j6bF1SreIMh83O1rOdYeGV6MyFZXs71Lt93a7swJbheb2v7cJkoupKKP5JWLRa+b",
	"bShIu486pJkh5muttlj09Yy2rAdMYif+aYVL9VdSv31nyf0c6J175uHu1jD5QSZn+pp7NyuGrWL/x1rA",
	"l3DHRK4MRNgrCC3ICnRz3a+stpsnTKZAUnvDVN0x1G+Rd0LItjDeW7bnqGxZmC9Zv84lN/HNntW+ACEp",
	"3bi2OV8CUuH6DUXOS5zxCx5lpuuHHVIsaEk2UwRpZqeFmLadMqUPVsCKfYLGQWvE/vs47a6IrD/WPMyk",
	"XlmWbOyFM5grpA4p67EVbC42O874cUCeKNnXnfPjwBAvbCoJ29iK53v92/Vt8+/dhPq5QU9Yo5XAv2eJ",
	"yMZpoAB9F4NR4i6KDKsz5mNghiw2HTKm0drRPVtJnHMbvS2r26Mq2kPZ7eESex1k9aUR7tVBac+ArtOc",
	"ydBwMSPhohv+XQcm/F2DpBbN1EFvF9cquNsGNn9rZFMdtbYnpF7AcLtjbM+wrZAPW48Qe2H4Fe9svu7B",
	"Suv1bMv7lcblIEL5o+8d2n20TV/ud7/2yO/R9/pfM6TtUZt5LmNfEBS7qbFdTVeGIZeB5oOpAKkWOnBm",
	"VKsIJRzud+4ETRUccxEHpTtl8A2hc+44G1VIIQ07I3eM2lDD4o9kq0RuoHenLD7nLr25Z0lSFser2vhO",
	"JLU7n1aFsy9E0vIaa4deTkY7Vwbfsrs5n9UvqF6ViVav9/qLr46vqgfEydYDZGw+w4yDcVu4Tr7uhTKO",
	"Gxdvj7/55fGWy5o3x3/JG+MPNnsEpX8U8ebFPHtaJnTbb6cfd/Ck+x9ZdauI5wpN9lKZqDyKQKllniQo",
	"9TXQ2D2dPxd25fZnPa5oW0xT5sp1ZVXqLhIUmrGO+9qJRLp/193/clm6/i6m7V34t8HfYXj6/JDmG3Mc",
	"1es9P2r7IebLge2ZK3LVALMdch/9Kh1r1CiMIhPQLaWkkfmOcNy4wCyRz5XfIWZFoS2i3L2JyXksODgw",
	"QsqrSC88JBfCoAgmvILX7IyYPZR3ndUSDvjUnCstBV+RSHDFlAYebUhA0LnTzLxEMsSbxu72rPj3G8X2",
	"ko29H5jzYiWLno6rH5q9aWIeGLcBvJXFUwDfpsaqy37jH5y0UIbDXdk7j7SqaXokecUFcYDw2lru4fO2",
	"VL6efjnjszIpzeOpWN+a+c9sEmmsSzG+Ssoy5WJDmFbERTJjce7ZGNt+XtYl72DndVmb9t6B/g+pLvzr",
	"0Nnl3dv4/DcaAEr/Oe1neYv2b2yxi1BuX9yXLwk37nHV8qk62fNGcUjs7Nt24ZsnxrkCRaY313POuNKI",
	"F2JJpsPrs58M9fryuj/8YAt4s+r7nA+ThBRXkC7rSt2tS8HailqqoxIW42ocbs7dSqYXcM1kDcNs1Xxd",
	"my6mmhYbmpT3n+Z9tbLXItVjdLelGjLbOr7N1qhe4/9ZbH5VuSt5VQ2I1pSvIN66X329k9EFpHYx0eKE",
	"Q0z+X84N/15W9hf6fXHxsuv138Bx/h6gcB75ZawwQ8wUbVnTtHpLZzvtFLq3eKS3Wyy5so9YnprAvXEJ",
	"np8IaXBSfwrTNuVgfz/Bfmuh9OAkPAmN4bqD7yaFjauJxjVNLZl2CVAptccPj/8XAAD//99ld5bsOgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
