// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xbe3PbOJL/KijuVtmuE2VKtvzQVupKYyuJdh1b68fe7oxyNkQ2JWxIgAOAtpWUv/tV",
	"A+BLYmJP4pnaur8SC69Go/HrX3eDX7xQpJngwLXyhl+8jEqaggZp/pqKhIWrSTSleol/R6BCyTLNBPeG",
	"3vUSiAQlchkCYRFwzWIGksRCEr0EkpnRXfIhV5rMgVByTxMWud/J5HTG9ZJqEgoeC5kqogUZjad+r98n",
	"En7NmYQU5RrOuE96/sEeCZdU0hClI4ngC/z9TDyADKkCkoDGlg7heTo3/6E8IstVtgSuiODJCvsbYZSm",
	"UpMHppeEunFlG/Co2UKEdFPOuNfx4JGmWQLe0FskYk4Tn+Z66ds9eR2PoWYy1FfH4zTFfpnTotfx3LYi",
	"b6hlDh1PhUtIKao2pY9nwBeo54O9jpcyXvzZ6+B8GiTO/L+/UP9z4B9/3Hb/8T9+CToHvafi953//rPX",
	"8fQqw5WVlowvvKenJ1xaZYIrMAc7SiTQaDV+ZMqeeyi4Bq7xvzTLEhZSPOTdfys86S/VptEGNGWJN3TG",
	"YXU1OSVbm+rYItSuQ8AuhOpRmvIQhQvCg8OD4CDwD+H4wD8YhODDUXDkQ48eHO3N4/3jo7nX8ZSmOlfe",
	"cD847niaaaP6y8LsNhZwOx+dXY5Hp/+6Hf9zcnV95T3VVf1nCbE39P60W5n+rm1Vu2MphbQKaxr711Z8",
	"6ng/0egSfs1B6e/U5FsGSUS2JCzEbSgi2CIpWiIX5tpAmulVU3WHx3v7UbwH/v78YM/f7x/P/XkQD/z5",
	"UbQ3CCDsHQygobqgUt2E21sorcikduNL7U3O/zE6m5zeji7f3XwYn1+/gv6+sexTx3sr5JxFEfDv1OC/",
	"RE4iYTS2pPdAVB7HLGTANclApkwpJrgBmAwkgg3RS6aIyECayZvqnffDvWgfBn58QA/9o+Og58/DCPy4",
	"19/bHxwc4i8N9e5V6p2Wy5EIOIOo0up0fPlhcnU1uTi/PR2fT8anr6BWxGC8cQi+IdUQkVyBJJEAVWmj",
	"UsE3NPDU8SYcUYYmVyDvQdo1v+88RpzkHB4zCFEkwJmICMNcSojIw5IlQDIpQlCK8YVxFs4umgfRiw6P",
	"guAw8I9ieugfHkSxHx8Hx37cnx8e74d0EByHtYMYNO3cboYosxsrRN3Er8eX56OzVzHttpWeOt650G9F",
	"zqMfA9hWYC0P2MBQU2vH88FBHAyofxAdDfzB/jzyo0N66EdBPDjsU9g7OqQN891vAVacOzbClyo7v7i+",
	"fXtxc376mnBarfPU8W44blJI9hm+V2n/MChTuxJo9aEEQ09oogiVULCLCK8DDdEM7W0o2ExTn7RnAcGH",
	"QXzg4+336TyMfKjhQUOfvUqfo6Ygpf8vlXpzPrq5fj8+v56cjK5fBRLWljTbctud55o8UGs4mRT3LIII",
	"6Q1ThFl8xvWNCs3gH4GAAvAvYSGIWnFNHwnjDS8Xo99r6roPR8e93mHPP47pkX90GAd+QHvU74fHx8Eg",
	"nB8Ex1Fd1/1+petK7vXL/nY0ORuf3k4vxycX56eT68nF+SsoemO9p3JOw6lK7TWHmZ9JQcdILJJEPCAM",
	"Xr49IYdHwSGZSjFPICWnRpfK8FhDjI/3ujM+41N7dIooLfNQ57LEWGaYtJUJafhoOiExZUkuQXUNfc0k",
	"Qr5mlgcWp7Uu4/s8pdxHokPnCRB4zBLK7bQqg5DFLMS7Y12IxXUeAhGxJf5W/u6MXy1FnkSFrREa4hRm",
	"ynVJI7iHBEVzclY0e5MdPWfSmwS4bmPre73h7Ne8JYBhqtprw4PxELrkRkGcJ9h1xrWk4Sc8QTyoCOb5",
	"YsH4Yn0fLyRtVi3e0Msl8yXEYBZs21JxCTYO7/p6SmwjQYXVpTBUsFyCcb3Xr6ZmXMMCjOtyd+oZu1B5",
	"mlK5Wjt3Yqarb/0lnLPal/1h45guJ6RUR3Faq4I+1Jfukms8PKZMS0i54CykyYzbU0SVuLPheeoNf9mk",
	"u52ar+usxxId73J8dXFzeTK+Hf/z/ejmCmG704oxHW/008Wlbb+4ub69eHt7OTp/N/Y63s355MP0bIzL",
	"meaSj2DT6B+jydnopzPseDoenZ5NznGxk/H41HRedxqdFm75sXEAmzt8qZ091aPWXzx3ts72CkP5WA4T",
	"839DqPEY3wNNbNqgiTlZazLhpDgmgu2FRdUccrWZpZ0Y5aLRBU9WRTT98htiZiDlJtbnXj2rBjd0Y98d",
	"79GnkPml4HbDSBAVjnOyf+x4WZJLmtS3g1w4AY0SuuwA44s8obLeyS1neaCfUk4XILtRmHaZ2HW9UNgz",
	"prQhkAzUpfM1m4ooWkgKStEFGOhLmNJ4rzI33PicCSrIpGOsK9rrE1wCdcgjKiOSgl6KqJG4afM4HB71",
	"bUYXcKvFJxvvrUU0+LORQ4KWDO6LK44jCY5E45Cg8kSrLpnENkA2WRqhZzyToIDrDo6RYOgeFyQVhvbZ",
	"QbgfAxFGBGLCIIo+APFbWZflgu+MSoVeZkXChFV7qgwGVn+9/zn9+fPP//w7u/j3zUP89zdv2kCtUObm",
	"ho0aRVykxQrLUSSlOlyuxUcklEyDZEjgmYZUPcdebBBRwapHpaSrDXsuxWu7yW6OFutxykaKQi6mI7J9",
	"kQEnLnAZLYDrnfV9WQbjliMRxIzbEBZpv2PJeQKK5CY2NPQRIdscTkg5nooKRQbRjGtBIhYb6NIkQQah",
	"yPa7s4ufRmdoDzdX48sd9AawMnZgFAoRoQuKdGDGnVKLtRI6B4ziEgi1kJZ3wT1NchNYM04yyYRkxtgi",
	"kGYnN2geaK1zoZcYaFANZHt6cXW9Y8bnWWR/GV2fvN/pkgvuOnVIxFSW0NUtpyl0Ztzq6Ra1b1OXJeNp",
	"xizbgNQptFaJpoFhJwvBTD7jdsGOSXhahq2IOybcQt2W5iJyigG5wJkNA907Pthpu7lW7FvN0hYguWYp",
	"KE3TjDwsgdfSv4ac2aGRc8xGKHPrcp3l2repWdwxzbVAThjSJFkRBbq+xUrhikyuLsjRQdAj1ovZJCRK",
	"9llwk++wILUfrF/XftA/8IOeHxxf94LhXjAMgp/rzhB155stvsC9NFSwrpEL8x+aEMuxAZlh2V4yJhvO",
	"K5LlMhPKGvkclvSeCdzuVZ5lQmrEAvkpEg/cbVi38MuxNQu1HvzWEZnQUAqlCE2SwmxUYRWZFFEe2nCG",
	"3zMpOA7xOvXUdD/YP2pTRM2SnyWN2GmjRlAytlVWnP4St8vQohVgZKNBxtTsr0LpOVRavYd1jbwziROy",
	"FhBPi1R9fV+DwXrOfWOTYAKXyO4vpnmiC8Nobvd/loCup34HmCI2ctDJygRB99Alp0yZCUs/63yVnvEK",
	"dKJcmsCigY8RhMwkNNc23DDTuRAJUJPXY9HLo561I2m7q3gAM87SNNfmQGmsQdo7zgQ3eEsmpwVWC3cP",
	"8EhtOAURuWd0xn/NQa6qWIAIXk7yF8LiRkjXqcEAWQAHSTVqjNzcTE4NLrw1cbSqVZBchglFEfwe97mp",
	"svYizusWY57FEeN3bgu/Y5IsUcSs2qYNDP42BHl/g5WPpoO8hUl0azbHZRyfDWmdRToXSBgPRYoWVrjC",
	"LlKjuuFWtmjOnsUGPIzIqpy4xk8E1/CouzM+wRNc86k4YfNI2xZCS8RFajLN+IlIU8HdfJ9gZcuCNaQa",
	"1hCsg7wUg/BOkVjAHjgAweSWRUObJ6/MH9scIg6L/xiowgYJCyb4kCxALCTNliZOsT9is2Ygq0H4F9lG",
	"nobdOiVD7hDQYXenaX9fvDrWDr1qC8ZwFvZcc+UDVdrvmYALMCAo5q8xu4qwtYdYZc7VRFgO9Z0DnZUM",
	"cPdLUa98mnldR5S/BgNf8dFfvYtm5W/cxlKI1mtZu3llx1e6gjXytam4K6SbTZdNamnQdaj8KjLOjLVY",
	"fjokI5wBTFGqbuyFizYqXSkNKQ5CKtsYUnY3l6XKVKFZNxg2OpUGiV0ykFSG1ogNkR0S5yn9WR4Ee0Bu",
	"VFHsdhkSK7PX8VCOZmqhbNrUqWPLDY9pajRN9U4LVm2hCzfklOzkNoTJMG5b7i8q/Ka6NeNLtkB/W5Jz",
	"wyQbu46ZVNqo35YHJOULGJKe3wuCwL4u6AXBkJy4S7VrFV96ZtMl6PkD7HRVRLz11kFgJxuihH4pStWl",
	"bua91iRcSh9ZiurGeYzTcX+25efK2KD9WQbGYiZycoo0OS9rpiagQLh9hDDXphzXIOwzXsfi6vXGRjbf",
	"hdFgZ3SErIjnSEbDTxir25So5Ss2sOsSB+VFXsQA+Wkx0FkK3gnxsBsBN882yvQDokfhG0kiFiwkc6qM",
	"dyKMZ7kB+csyTxhRTUksRVq/u8AXjEMhfhVhMmV36bxdEc3VwriyXLqJXMV+c738jFM39kHekJgmyqxp",
	"f/gy48QK3MUr220Wcd+8IQhUa32kSACbZh6NUsZn3ow/GTHqfGUw2Dt4lsva7XxXLJdQpZ06fmtA50Y1",
	"HQYqmvIVSUWEAFYh5esFeoPh/uAHAr2n35rkW3eltyx6aqT8ymxLI8dX+rlv5vhcrydTkGI8FkV9joba",
	"G37ZLAeOp34o0ixhlGtyOb66tlUhIYmZGcnfN1M3rAoRT08+FD0+OKnKXJqd1Pp97It/j/mS8tDeWySy",
	"QtFEke3ReLqznjhUtpRSqNQXkgHXNmpmC95xtBGlPbm8Oa3dRLOV6VryzMj1pz+Rv8GKvAWqc2lx+m2e",
	"JK0TOAu3yi7Iogu/TQeb//OrGMbSHzRhvwhIIjI5tcsk8MiQAcQs0SCL2lCG6jaLYqcplZrRxF0L5XJE",
	"ZNemY3awS/PwbP1iSXmUML4wBp+wEFxm1702G2U0XALpdwOv4+XSZJi1ztRwd/fh4aFLTXNXyMWuG6t2",
	"zyYn4/Orsd/vBt2lTpNaAchrHjeeqtfx7kEqa133PZpkS9rDISIDTjPmDb29btDds4RtaeKWIjM9/OIt",
	"QH81IR8uIfxktL1paW7p8tgmEZIP0O+rakDtgVs/CF5Qt35ZAfh9kVXfuFtXjvIzRYrCgakB27LY2r5M",
	"0249D9yqijOGrK68eQbwVM0OKxvqVNZlE4aGI9nMkDH+t0WzAVNzK+/skLta2G1WOBmf+UqvbK1Xgn0v",
	"ZRzzXY0av9mybG/rzrS4jMgbRM27zb7IFbfI6PyUrHU0wl04YWuyGflv56uadE6Ektqp8I5sO9e602xD",
	"NVop6ukoM8T8WstfFn037KleNTH2W72G/eUHCxVnQO/dYz5XNcboC4mp6WsqylYNayWSuxp/kXDPRK4M",
	"TtrCjRZkAbq57gtrFOapqknC1N6qVpWZ+vuIDY+4rowPlrw6Zl6WM8pgReeSG3dt92pfmJGUrlzbjMeA",
	"zL5e18l5Cbadghaa6QZBlxQL2piBKYKsudvCs9t2mdJHq2DFPkNjo7U45cco+qaK7G2s3S8T+WVZsrJP",
	"KcAU3rqkzPlWvmO+2riKd0PSLHTUb+Td0NBHbCpp59hq5Ucvtevbdq03I/nnBn3FCO3Gf5sBYkxBfQV4",
	"ZdERJ66q5iogWlh0JPNVl4xpuHSk1SYpZ9wyF8tNt6gKt1B3W7jEVhdjk9L2tupYtGWQ1h2YiTNxMaPh",
	"ohv+v45H+HcNiVpOpo51m3BWodw6nnXWRjaPo9b2Fa0X6Nt+H9ZnWD+Qj7+jA26tZbe440YlFRH8qePt",
	"Wznapi/l3a294DZDes8PaTxVNIP2nh9UPXN+6niDl0jW9iS3STHMpmsBhaYLE4SUbuyjSW+pFqpxYixI",
	"EUo4PGzUaU0eHwM3B9QbifwVoTPuaDFVyNINASb3jFpHxqI7spbkN8C+kdifcRcLPrAkKdP7VXZ/w09b",
	"yadVYvAbfrosxG0w+MnpRtHje6Sb8ct6iW27jEr7/Z1vfrtyVX2Gkqx9xoLNJxjUMW7z7snLvnPBcePi",
	"C5bv/n5lDRlY5H3vpyq/8TuVj/ZVAij9k4hWrwYg0zJmXv8E52kDtnq/y6prGU+XlbNlcaJy8wY5zpME",
	"tb4EGrkPsM6EXbn9OZzLSBfT1B5LVQLWnja5KJBmrOt+7YYi3b3v7X477V5/Kdb2bdF/NMruB8fPj2h+",
	"DoWj+v3nR62/k349TD9xiccaLrcjez2irBVurLkkoFuye6fmdwT9RqG3xFdXwYCIFbnPkHL3GirnkeDg",
	"IA9puyL9YJ+cC4NVwDURvGbNxMhQ1oSrJRy8qhlXWgq+IKHgiikNPFwRnyCEpJl5g2aCBxo1HgNW4iUr",
	"W2KZ8WIli9Eu3tg3smliPsJocyNWF19zI22nWHXZbXwc2cJ/9jd17+69PZrmvSfbXBAHOzt/6P3Yf35E",
	"+SHL65m4VX1phV8jLq0pkksbbxsjto8mC/IyXxGmFXFu2Ri2e5fI1t8v9sg72Hi+2GYk70D/ThYS/HGu",
	"xqUo1p3N/387w0N+zsgyqsOWevmNy8tSbr+yKt/Ertx7wayRwCXbNm/7vOntEzv1hvWRiSa5AkVMJnjG",
	"DYv769XFOfmAU5OpeW6B/LJ4qdclF8gOy495XLhLJRTVlr/MuEiZ1s3GBGJNch4uKV9AZJNPdzxPkjuE",
	"3DABKkvC78YVWcUibe32sP3BZauvgLs3IjazZdZaiZw8UK7NrGYx6wscozYas/UCcwgzLrhLhpQqrwIS",
	"52T861UG9hNZDN3v6tfGTOibuf4Lr9BdIfWkLMqb70mUrf1VH984eWu+zhWrttmCCwkRYTFRCM42vKd6",
	"if+yyPxVJTvIdjWF0+7aM4CdjRSAT2r1uBYEspp+PRB6CcFeV+TvQ7b/QAQsznMT//5zqetvhMzv47qv",
	"BLQODr6NtWaImcLarq1PYUiyW1WSPpZDN0P5Rs2uUb+spUBc2Fqu+/Tx6f8CAAD//0e1oA/oQgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
